### PR TITLE
change id'add-product-form' to class to ...

### PR DESCRIPTION
**Pull request by tyranni**
avoid same id's when using 'addtocard' in product list

### CODE REVIEW

**Comment by extcode** [comment]
Please tell me why you would add time measure units? Usualy comparative prices needed for goods that can be measured by weight, volume, length or piece per package. Do you have products with a timespan you would compare like a journey. Should the customer compare the prices per day (hour)? What products do you think about?
If I can follow your arguments I only would merge this second commit in a new ticket. I think this is a new topic and does not belongs to the ids in add-product-form.

**Comment by tyranni** [comment]
Hi Daniel,
I'm working on a course/event booking system where one special
requirement is to book courses if possible for hole days.
If a course lasts only a quater of a day the customer should be
encouraged to book more courses to fill the day.

The add-product-form-thing has nothing to do with the above ;). This is
only relevant if one likes to list all products in one list. Adding
"<f:render partial="Product/CartForm" ...." to list.html leeds to
multiple adding of "id="add-product-form"".

Best wishes!
Kerstin

Am 11.12.16 um 20:14 schrieb Daniel Lorenz:

**Comment by extcode** [comment]
OK, in this case I would recommend to extend the product model in your sitepackage-extension with an additional field or add the options through PageTS to the product.
The basic idea of this fields is to calulate the price to a given baseunit.
An example. If you sell different coffees in differen package units you have to show the price of a single coffee package to a given baseunit in your shop. In case of coffee kilogram will be a proper baseunit. The customer should be able to compare the different coffee package by the price per kilogram.
In your case you won't compare the cources by price.
In the case adding this to the extension we have to add some more times and the conversion factors from one time unit to all others. And some more tests.
I think time is not a typical unit for baseprice calculation.

I mention to add a new field to the product or use and extend the option list if you don't need the baseprice calculation for other products.

**Comment by tyranni** [comment]
good idea ;) 
to be honest, i didn't noticed that the time-thing was added to my previous pull request. I only thought that the add-product-form-thing could possibly be relevant for others. Sorry, if this led to some confusion ;)

**Comment by mkoitka** [comment]
I just stumbled upon the same issue. Listening on a class or on the existing attribute data-remote would be more versatile.

**Comment by extcode** [comment]
I'll close this PR. I'll check it in current version.

**Pull request closed without merging**
