### PR TITLE
[FEATURE] Use buyerEmailFrom for replyTo instead of TYPO3-defaultMailReplyToAddress

### PR DESCRIPTION
**Pull request by nebrot**

### CODE REVIEW

**Review by extcode — COMMENTED** [review]
Do you need to setReplyTo? It should be the email address the email comes from that is automatically replied to, right?

**Comment by nebrot** [comment]
We are using TYPO3 9.5.23 with Cart 6.10.0 and this mail-settings:

```
LocalConfiguration.php:
['MAIL']['defaultMailReplyToAddress'] = 'a@example.de';

TypoScript:
plugin.tx_cart.mail.buyer.fromAddress = b@example.de
plugin.tx_cart.mail.seller.fromAddress = b@example.de
plugin.tx_cart.mail.seller.toAddress = b@example.de
```

The mail to buyer comes correctly from b@example.de, but reply-to is not correct and goes to a@example.de (LocalConfiguration) instead of fromAddress in TypoScript.

**Comment by extcode** [comment]
I'm working on that. But I'll add a new configuration for the Reply To address instead of using the from address.
This will avoid the breaking change and allow to configure c@example.com as the Reply To address.

I'll test the code for cart v6.x and v7.x and I'll make a release today.

**Comment by extcode** [comment]
Hope the replyToAddress configuration fulfills your wish to set the Reply To address for buyer emails.

**Comment by nebrot** [comment]
Thank you Daniel, we'll test it👍🏻

**Pull request closed without merging**
