### PR TITLE
[BUGFIX] Fix TCA leading to duplicate tax entries in fields tax/total_tax

### PR DESCRIPTION
**Pull request by johfeu**
Relates: #312

### CODE REVIEW

**Comment by extcode** [comment]
I think this will be resolved with #529. Can you test the change please and if solved, close your PR please.

**Comment by rintisch** [comment]
@johfeu I guess this PR can be closed as it is solved with #529!?

**Comment by johfeu** [comment]
verified works with 529

**Comment by rintisch** [comment]
Thanks for the feedback. I will close this PR.

**Pull request closed without merging**
