### PR TITLE
[BUGFIX] Fix module access

### PR DESCRIPTION
**Pull request by johfeu**
#535

### CODE REVIEW

**Comment by rintisch** [comment]
@johfeu Thanks for the contribution. 
I tested it but it's unfortunately not working for me this way. 

For `cart_cart_main` you set `'access' => ''`. In my opinion it needs to be `'access' => 'user'`. Or do I miss something?

**Comment by johfeu** [comment]
@rintisch how does it behave for you?
My observation is: if i set `'access' => 'user'` for `cart_cart_main` as well, then i have to explicitly grant access to the main module. If i leave it empty, it will only display the main, if the submdule is accessible. On a first view, i was not able to find the logic in the core.  I just replicated how the core and other extension are doing it:

e.g. filelist in core 
filelist module with 'user'
https://github.com/TYPO3/typo3/blob/main/typo3/sysext/filelist/Configuration/Backend/Modules.php
parent without access in
https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Configuration/Backend/Modules.php

Or another community extension
https://github.com/cobwebch/external_import/blob/master/Configuration/Backend/Modules.php

**Comment by rintisch** [comment]
Thanks for ll the information. I did not know this, I just used your link from the docs as point of truth and there an empty value is not named. Your latest comment is convincing with all the examples :)

**Review by rintisch — APPROVED** [review]
Works as expected.

**Review by extcode — APPROVED** [review]

**Pull request merged**
